// Generated by `wit-bindgen` 0.34.0. DO NOT EDIT!
#include "viz.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `viz:component/viz-api`



__attribute__((__weak__, __export_name__("cabi_post_viz:component/viz-api#get-graphviz-version")))
void __wasm_export_exports_viz_component_viz_api_get_graphviz_version_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + 4))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

__attribute__((__weak__, __export_name__("cabi_post_viz:component/viz-api#get-plugin-list")))
void __wasm_export_exports_viz_component_viz_api_get_plugin_list_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + 4));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 8;
      (void) base;
      if ((*((size_t*) (base + 4))) > 0) {
        free(*((uint8_t **) (base + 0)));
      }
    }
    free(ptr);
  }
}


__attribute__((__weak__, __export_name__("cabi_post_viz:component/viz-api#read-one-graph")))
void __wasm_export_exports_viz_component_viz_api_read_one_graph_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + 8))) > 0) {
        free(*((uint8_t **) (arg0 + 4)));
      }
      break;
    }
  }
}









__attribute__((__weak__, __export_name__("cabi_post_viz:component/viz-api#layout")))
void __wasm_export_exports_viz_component_viz_api_layout_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + 8))) > 0) {
        free(*((uint8_t **) (arg0 + 4)));
      }
      break;
    }
  }
}


__attribute__((__weak__, __export_name__("cabi_post_viz:component/viz-api#render")))
void __wasm_export_exports_viz_component_viz_api_render_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      if ((*((size_t*) (arg0 + 8))) > 0) {
        free(*((uint8_t **) (arg0 + 4)));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + 8))) > 0) {
        free(*((uint8_t **) (arg0 + 4)));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_viz:component/viz-api#render-dot")))
void __wasm_export_exports_viz_component_viz_api_render_dot_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      if ((*((size_t*) (arg0 + 8))) > 0) {
        free(*((uint8_t **) (arg0 + 4)));
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + 8))) > 0) {
        free(*((uint8_t **) (arg0 + 4)));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("[export]viz:component/viz-api"), __import_name__("[resource-drop]graph")))
extern void __wasm_import_exports_viz_component_viz_api_graph_drop(int32_t handle);

void exports_viz_component_viz_api_graph_drop_own(exports_viz_component_viz_api_own_graph_t handle) {
  __wasm_import_exports_viz_component_viz_api_graph_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]viz:component/viz-api"), __import_name__("[resource-new]graph")))
extern int32_t __wasm_import_exports_viz_component_viz_api_graph_new(int32_t);

__attribute__((__import_module__("[export]viz:component/viz-api"), __import_name__("[resource-rep]graph")))
extern int32_t __wasm_import_exports_viz_component_viz_api_graph_rep(int32_t);

exports_viz_component_viz_api_own_graph_t exports_viz_component_viz_api_graph_new(exports_viz_component_viz_api_graph_t *rep) {
  return (exports_viz_component_viz_api_own_graph_t) { __wasm_import_exports_viz_component_viz_api_graph_new((int32_t) rep) };
}

exports_viz_component_viz_api_graph_t* exports_viz_component_viz_api_graph_rep(exports_viz_component_viz_api_own_graph_t handle) {
  return (exports_viz_component_viz_api_graph_t*) __wasm_import_exports_viz_component_viz_api_graph_rep(handle.__handle);
}

__attribute__((__export_name__("viz:component/viz-api#[dtor]graph")))
void __wasm_export_exports_viz_component_viz_api_graph_dtor(exports_viz_component_viz_api_graph_t* arg) {
  exports_viz_component_viz_api_graph_destructor(arg);
}

__attribute__((__import_module__("[export]viz:component/viz-api"), __import_name__("[resource-drop]node")))
extern void __wasm_import_exports_viz_component_viz_api_node_drop(int32_t handle);

void exports_viz_component_viz_api_node_drop_own(exports_viz_component_viz_api_own_node_t handle) {
  __wasm_import_exports_viz_component_viz_api_node_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]viz:component/viz-api"), __import_name__("[resource-new]node")))
extern int32_t __wasm_import_exports_viz_component_viz_api_node_new(int32_t);

__attribute__((__import_module__("[export]viz:component/viz-api"), __import_name__("[resource-rep]node")))
extern int32_t __wasm_import_exports_viz_component_viz_api_node_rep(int32_t);

exports_viz_component_viz_api_own_node_t exports_viz_component_viz_api_node_new(exports_viz_component_viz_api_node_t *rep) {
  return (exports_viz_component_viz_api_own_node_t) { __wasm_import_exports_viz_component_viz_api_node_new((int32_t) rep) };
}

exports_viz_component_viz_api_node_t* exports_viz_component_viz_api_node_rep(exports_viz_component_viz_api_own_node_t handle) {
  return (exports_viz_component_viz_api_node_t*) __wasm_import_exports_viz_component_viz_api_node_rep(handle.__handle);
}

__attribute__((__export_name__("viz:component/viz-api#[dtor]node")))
void __wasm_export_exports_viz_component_viz_api_node_dtor(exports_viz_component_viz_api_node_t* arg) {
  exports_viz_component_viz_api_node_destructor(arg);
}

__attribute__((__import_module__("[export]viz:component/viz-api"), __import_name__("[resource-drop]edge")))
extern void __wasm_import_exports_viz_component_viz_api_edge_drop(int32_t handle);

void exports_viz_component_viz_api_edge_drop_own(exports_viz_component_viz_api_own_edge_t handle) {
  __wasm_import_exports_viz_component_viz_api_edge_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]viz:component/viz-api"), __import_name__("[resource-new]edge")))
extern int32_t __wasm_import_exports_viz_component_viz_api_edge_new(int32_t);

__attribute__((__import_module__("[export]viz:component/viz-api"), __import_name__("[resource-rep]edge")))
extern int32_t __wasm_import_exports_viz_component_viz_api_edge_rep(int32_t);

exports_viz_component_viz_api_own_edge_t exports_viz_component_viz_api_edge_new(exports_viz_component_viz_api_edge_t *rep) {
  return (exports_viz_component_viz_api_own_edge_t) { __wasm_import_exports_viz_component_viz_api_edge_new((int32_t) rep) };
}

exports_viz_component_viz_api_edge_t* exports_viz_component_viz_api_edge_rep(exports_viz_component_viz_api_own_edge_t handle) {
  return (exports_viz_component_viz_api_edge_t*) __wasm_import_exports_viz_component_viz_api_edge_rep(handle.__handle);
}

__attribute__((__export_name__("viz:component/viz-api#[dtor]edge")))
void __wasm_export_exports_viz_component_viz_api_edge_dtor(exports_viz_component_viz_api_edge_t* arg) {
  exports_viz_component_viz_api_edge_destructor(arg);
}

__attribute__((__import_module__("[export]viz:component/viz-api"), __import_name__("[resource-drop]context")))
extern void __wasm_import_exports_viz_component_viz_api_context_drop(int32_t handle);

void exports_viz_component_viz_api_context_drop_own(exports_viz_component_viz_api_own_context_t handle) {
  __wasm_import_exports_viz_component_viz_api_context_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]viz:component/viz-api"), __import_name__("[resource-new]context")))
extern int32_t __wasm_import_exports_viz_component_viz_api_context_new(int32_t);

__attribute__((__import_module__("[export]viz:component/viz-api"), __import_name__("[resource-rep]context")))
extern int32_t __wasm_import_exports_viz_component_viz_api_context_rep(int32_t);

exports_viz_component_viz_api_own_context_t exports_viz_component_viz_api_context_new(exports_viz_component_viz_api_context_t *rep) {
  return (exports_viz_component_viz_api_own_context_t) { __wasm_import_exports_viz_component_viz_api_context_new((int32_t) rep) };
}

exports_viz_component_viz_api_context_t* exports_viz_component_viz_api_context_rep(exports_viz_component_viz_api_own_context_t handle) {
  return (exports_viz_component_viz_api_context_t*) __wasm_import_exports_viz_component_viz_api_context_rep(handle.__handle);
}

__attribute__((__export_name__("viz:component/viz-api#[dtor]context")))
void __wasm_export_exports_viz_component_viz_api_context_dtor(exports_viz_component_viz_api_context_t* arg) {
  exports_viz_component_viz_api_context_destructor(arg);
}

void exports_viz_component_viz_api_object_free(exports_viz_component_viz_api_object_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    case 2: {
      break;
    }
  }
}

void viz_list_string_free(viz_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    viz_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      viz_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_viz_component_viz_api_result_own_graph_string_free(exports_viz_component_viz_api_result_own_graph_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    viz_string_free(&ptr->val.err);
  }
}

void exports_viz_component_viz_api_result_void_string_free(exports_viz_component_viz_api_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    viz_string_free(&ptr->val.err);
  }
}

void exports_viz_component_viz_api_result_string_string_free(exports_viz_component_viz_api_result_string_string_t *ptr) {
  if (!ptr->is_err) {
    viz_string_free(&ptr->val.ok);
  } else {
    viz_string_free(&ptr->val.err);
  }
}

void viz_string_set(viz_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void viz_string_dup(viz_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void viz_string_free(viz_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[12];

__attribute__((__export_name__("viz:component/viz-api#set-y-invert")))
void __wasm_export_exports_viz_component_viz_api_set_y_invert(int32_t arg) {
  exports_viz_component_viz_api_set_y_invert(arg);
}

__attribute__((__export_name__("viz:component/viz-api#set-reduce")))
void __wasm_export_exports_viz_component_viz_api_set_reduce(int32_t arg) {
  exports_viz_component_viz_api_set_reduce(arg);
}

__attribute__((__export_name__("viz:component/viz-api#get-graphviz-version")))
uint8_t * __wasm_export_exports_viz_component_viz_api_get_graphviz_version(void) {
  viz_string_t ret;
  exports_viz_component_viz_api_get_graphviz_version(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + 4)) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("viz:component/viz-api#get-plugin-list")))
uint8_t * __wasm_export_exports_viz_component_viz_api_get_plugin_list(uint8_t * arg, size_t arg0) {
  viz_string_t arg1 = (viz_string_t) { (uint8_t*)(arg), (arg0) };
  viz_list_string_t ret;
  exports_viz_component_viz_api_get_plugin_list(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + 4)) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("viz:component/viz-api#create-graph")))
int32_t __wasm_export_exports_viz_component_viz_api_create_graph(uint8_t * arg, size_t arg0, int32_t arg1, int32_t arg2) {
  viz_string_t arg3 = (viz_string_t) { (uint8_t*)(arg), (arg0) };
  exports_viz_component_viz_api_own_graph_t ret = exports_viz_component_viz_api_create_graph(&arg3, arg1, arg2);
  return (ret).__handle;
}

__attribute__((__export_name__("viz:component/viz-api#read-one-graph")))
uint8_t * __wasm_export_exports_viz_component_viz_api_read_one_graph(uint8_t * arg, size_t arg0) {
  viz_string_t arg1 = (viz_string_t) { (uint8_t*)(arg), (arg0) };
  exports_viz_component_viz_api_result_own_graph_string_t ret;
  exports_viz_component_viz_api_own_graph_t ok;
  viz_string_t err;
  ret.is_err = !exports_viz_component_viz_api_read_one_graph(&arg1, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const viz_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + 8)) = (*payload2).len;
    *((uint8_t **)(ptr + 4)) = (uint8_t *) (*payload2).ptr;
  } else {
    const exports_viz_component_viz_api_own_graph_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 4)) = (*payload).__handle;
  }
  return ptr;
}

__attribute__((__export_name__("viz:component/viz-api#add-node")))
int32_t __wasm_export_exports_viz_component_viz_api_add_node(int32_t arg, uint8_t * arg0, size_t arg1) {
  viz_string_t arg2 = (viz_string_t) { (uint8_t*)(arg0), (arg1) };
  exports_viz_component_viz_api_own_node_t ret = exports_viz_component_viz_api_add_node(((exports_viz_component_viz_api_graph_t*) arg), &arg2);
  return (ret).__handle;
}

__attribute__((__export_name__("viz:component/viz-api#add-edge")))
int32_t __wasm_export_exports_viz_component_viz_api_add_edge(int32_t arg, uint8_t * arg0, size_t arg1, uint8_t * arg2, size_t arg3) {
  viz_string_t arg4 = (viz_string_t) { (uint8_t*)(arg0), (arg1) };
  viz_string_t arg5 = (viz_string_t) { (uint8_t*)(arg2), (arg3) };
  exports_viz_component_viz_api_own_edge_t ret = exports_viz_component_viz_api_add_edge(((exports_viz_component_viz_api_graph_t*) arg), &arg4, &arg5);
  return (ret).__handle;
}

__attribute__((__export_name__("viz:component/viz-api#add-subgraph")))
int32_t __wasm_export_exports_viz_component_viz_api_add_subgraph(int32_t arg, uint8_t * arg0, size_t arg1) {
  viz_string_t arg2 = (viz_string_t) { (uint8_t*)(arg0), (arg1) };
  exports_viz_component_viz_api_own_graph_t ret = exports_viz_component_viz_api_add_subgraph(((exports_viz_component_viz_api_graph_t*) arg), &arg2);
  return (ret).__handle;
}

__attribute__((__export_name__("viz:component/viz-api#set-default-graph-attribute")))
void __wasm_export_exports_viz_component_viz_api_set_default_graph_attribute(int32_t arg, uint8_t * arg0, size_t arg1, uint8_t * arg2, size_t arg3) {
  viz_string_t arg4 = (viz_string_t) { (uint8_t*)(arg0), (arg1) };
  viz_string_t arg5 = (viz_string_t) { (uint8_t*)(arg2), (arg3) };
  exports_viz_component_viz_api_set_default_graph_attribute(((exports_viz_component_viz_api_graph_t*) arg), &arg4, &arg5);
}

__attribute__((__export_name__("viz:component/viz-api#set-default-node-attribute")))
void __wasm_export_exports_viz_component_viz_api_set_default_node_attribute(int32_t arg, uint8_t * arg0, size_t arg1, uint8_t * arg2, size_t arg3) {
  viz_string_t arg4 = (viz_string_t) { (uint8_t*)(arg0), (arg1) };
  viz_string_t arg5 = (viz_string_t) { (uint8_t*)(arg2), (arg3) };
  exports_viz_component_viz_api_set_default_node_attribute(((exports_viz_component_viz_api_graph_t*) arg), &arg4, &arg5);
}

__attribute__((__export_name__("viz:component/viz-api#set-default-edge-attribute")))
void __wasm_export_exports_viz_component_viz_api_set_default_edge_attribute(int32_t arg, uint8_t * arg0, size_t arg1, uint8_t * arg2, size_t arg3) {
  viz_string_t arg4 = (viz_string_t) { (uint8_t*)(arg0), (arg1) };
  viz_string_t arg5 = (viz_string_t) { (uint8_t*)(arg2), (arg3) };
  exports_viz_component_viz_api_set_default_edge_attribute(((exports_viz_component_viz_api_graph_t*) arg), &arg4, &arg5);
}

__attribute__((__export_name__("viz:component/viz-api#set-attribute")))
void __wasm_export_exports_viz_component_viz_api_set_attribute(int32_t arg, int32_t arg0, uint8_t * arg1, size_t arg2, uint8_t * arg3, size_t arg4) {
  exports_viz_component_viz_api_object_t variant;
  variant.tag = arg;
  switch ((int32_t) variant.tag) {
    case 0: {
      variant.val.graph = (exports_viz_component_viz_api_own_graph_t) { arg0 };
      break;
    }
    case 1: {
      variant.val.node = (exports_viz_component_viz_api_own_node_t) { arg0 };
      break;
    }
    case 2: {
      variant.val.edge = (exports_viz_component_viz_api_own_edge_t) { arg0 };
      break;
    }
  }
  exports_viz_component_viz_api_object_t arg5 = variant;
  viz_string_t arg6 = (viz_string_t) { (uint8_t*)(arg1), (arg2) };
  viz_string_t arg7 = (viz_string_t) { (uint8_t*)(arg3), (arg4) };
  exports_viz_component_viz_api_set_attribute(&arg5, &arg6, &arg7);
}

__attribute__((__export_name__("viz:component/viz-api#create-context")))
int32_t __wasm_export_exports_viz_component_viz_api_create_context(void) {
  exports_viz_component_viz_api_own_context_t ret = exports_viz_component_viz_api_create_context();
  return (ret).__handle;
}

__attribute__((__export_name__("viz:component/viz-api#layout")))
uint8_t * __wasm_export_exports_viz_component_viz_api_layout(int32_t arg, int32_t arg0, uint8_t * arg1, size_t arg2) {
  viz_string_t arg3 = (viz_string_t) { (uint8_t*)(arg1), (arg2) };
  exports_viz_component_viz_api_result_void_string_t ret;
  viz_string_t err;
  ret.is_err = !exports_viz_component_viz_api_layout(((exports_viz_component_viz_api_context_t*) arg), ((exports_viz_component_viz_api_graph_t*) arg0), &arg3, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const viz_string_t *payload4 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + 8)) = (*payload4).len;
    *((uint8_t **)(ptr + 4)) = (uint8_t *) (*payload4).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

__attribute__((__export_name__("viz:component/viz-api#free-layout")))
void __wasm_export_exports_viz_component_viz_api_free_layout(int32_t arg, int32_t arg0) {
  exports_viz_component_viz_api_free_layout(((exports_viz_component_viz_api_context_t*) arg), ((exports_viz_component_viz_api_graph_t*) arg0));
}

__attribute__((__export_name__("viz:component/viz-api#render")))
uint8_t * __wasm_export_exports_viz_component_viz_api_render(int32_t arg, int32_t arg0, uint8_t * arg1, size_t arg2) {
  viz_string_t arg3 = (viz_string_t) { (uint8_t*)(arg1), (arg2) };
  exports_viz_component_viz_api_result_string_string_t ret;
  viz_string_t ok;
  viz_string_t err;
  ret.is_err = !exports_viz_component_viz_api_render(((exports_viz_component_viz_api_context_t*) arg), ((exports_viz_component_viz_api_graph_t*) arg0), &arg3, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const viz_string_t *payload4 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + 8)) = (*payload4).len;
    *((uint8_t **)(ptr + 4)) = (uint8_t *) (*payload4).ptr;
  } else {
    const viz_string_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + 8)) = (*payload).len;
    *((uint8_t **)(ptr + 4)) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("viz:component/viz-api#render-dot")))
uint8_t * __wasm_export_exports_viz_component_viz_api_render_dot(int32_t arg, uint8_t * arg0, size_t arg1, uint8_t * arg2, size_t arg3, uint8_t * arg4, size_t arg5) {
  viz_string_t arg6 = (viz_string_t) { (uint8_t*)(arg0), (arg1) };
  viz_string_t arg7 = (viz_string_t) { (uint8_t*)(arg2), (arg3) };
  viz_string_t arg8 = (viz_string_t) { (uint8_t*)(arg4), (arg5) };
  exports_viz_component_viz_api_result_string_string_t ret;
  viz_string_t ok;
  viz_string_t err;
  ret.is_err = !exports_viz_component_viz_api_render_dot(((exports_viz_component_viz_api_context_t*) arg), &arg6, &arg7, &arg8, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const viz_string_t *payload9 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + 8)) = (*payload9).len;
    *((uint8_t **)(ptr + 4)) = (uint8_t *) (*payload9).ptr;
  } else {
    const viz_string_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + 8)) = (*payload).len;
    *((uint8_t **)(ptr + 4)) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_viz(void);
void __component_type_object_force_link_viz_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_viz();
}
