// Generated by `wit-bindgen` 0.34.0. DO NOT EDIT!
#ifndef __BINDINGS_VIZ_H
#define __BINDINGS_VIZ_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct viz_string_t {
  uint8_t*ptr;
  size_t len;
} viz_string_t;

typedef struct exports_viz_component_viz_api_own_graph_t {
  int32_t __handle;
} exports_viz_component_viz_api_own_graph_t;

typedef struct exports_viz_component_viz_api_graph_t exports_viz_component_viz_api_graph_t;

typedef exports_viz_component_viz_api_graph_t* exports_viz_component_viz_api_borrow_graph_t;

typedef struct exports_viz_component_viz_api_own_node_t {
  int32_t __handle;
} exports_viz_component_viz_api_own_node_t;

typedef struct exports_viz_component_viz_api_node_t exports_viz_component_viz_api_node_t;

typedef exports_viz_component_viz_api_node_t* exports_viz_component_viz_api_borrow_node_t;

typedef struct exports_viz_component_viz_api_own_edge_t {
  int32_t __handle;
} exports_viz_component_viz_api_own_edge_t;

typedef struct exports_viz_component_viz_api_edge_t exports_viz_component_viz_api_edge_t;

typedef exports_viz_component_viz_api_edge_t* exports_viz_component_viz_api_borrow_edge_t;

typedef struct exports_viz_component_viz_api_own_context_t {
  int32_t __handle;
} exports_viz_component_viz_api_own_context_t;

typedef struct exports_viz_component_viz_api_context_t exports_viz_component_viz_api_context_t;

typedef exports_viz_component_viz_api_context_t* exports_viz_component_viz_api_borrow_context_t;

typedef struct exports_viz_component_viz_api_object_t {
  uint8_t tag;
  union {
    exports_viz_component_viz_api_own_graph_t     graph;
    exports_viz_component_viz_api_own_node_t     node;
    exports_viz_component_viz_api_own_edge_t     edge;
  } val;
} exports_viz_component_viz_api_object_t;

#define EXPORTS_VIZ_COMPONENT_VIZ_API_OBJECT_GRAPH 0
#define EXPORTS_VIZ_COMPONENT_VIZ_API_OBJECT_NODE 1
#define EXPORTS_VIZ_COMPONENT_VIZ_API_OBJECT_EDGE 2

typedef struct {
  viz_string_t *ptr;
  size_t len;
} viz_list_string_t;

typedef struct {
  bool is_err;
  union {
    exports_viz_component_viz_api_own_graph_t ok;
    viz_string_t err;
  } val;
} exports_viz_component_viz_api_result_own_graph_string_t;

typedef struct {
  bool is_err;
  union {
    viz_string_t err;
  } val;
} exports_viz_component_viz_api_result_void_string_t;

typedef struct {
  bool is_err;
  union {
    viz_string_t ok;
    viz_string_t err;
  } val;
} exports_viz_component_viz_api_result_string_string_t;

// Exported Functions from `viz:component/viz-api`
void exports_viz_component_viz_api_set_y_invert(int32_t value);
void exports_viz_component_viz_api_set_reduce(int32_t value);
void exports_viz_component_viz_api_get_graphviz_version(viz_string_t *ret);
void exports_viz_component_viz_api_get_plugin_list(viz_string_t *kind, viz_list_string_t *ret);
exports_viz_component_viz_api_own_graph_t exports_viz_component_viz_api_create_graph(viz_string_t *name, bool directed, bool strict);
bool exports_viz_component_viz_api_read_one_graph(viz_string_t *dot_string, exports_viz_component_viz_api_own_graph_t *ret, viz_string_t *err);
exports_viz_component_viz_api_own_node_t exports_viz_component_viz_api_add_node(exports_viz_component_viz_api_borrow_graph_t g, viz_string_t *name);
exports_viz_component_viz_api_own_edge_t exports_viz_component_viz_api_add_edge(exports_viz_component_viz_api_borrow_graph_t g, viz_string_t *u_name, viz_string_t *v_name);
exports_viz_component_viz_api_own_graph_t exports_viz_component_viz_api_add_subgraph(exports_viz_component_viz_api_borrow_graph_t g, viz_string_t *name);
void exports_viz_component_viz_api_set_default_graph_attribute(exports_viz_component_viz_api_borrow_graph_t g, viz_string_t *name, viz_string_t *value);
void exports_viz_component_viz_api_set_default_node_attribute(exports_viz_component_viz_api_borrow_graph_t g, viz_string_t *name, viz_string_t *value);
void exports_viz_component_viz_api_set_default_edge_attribute(exports_viz_component_viz_api_borrow_graph_t g, viz_string_t *name, viz_string_t *value);
void exports_viz_component_viz_api_set_attribute(exports_viz_component_viz_api_object_t *obj, viz_string_t *name, viz_string_t *value);
exports_viz_component_viz_api_own_context_t exports_viz_component_viz_api_create_context(void);
bool exports_viz_component_viz_api_layout(exports_viz_component_viz_api_borrow_context_t ctx, exports_viz_component_viz_api_borrow_graph_t g, viz_string_t *engine, viz_string_t *err);
void exports_viz_component_viz_api_free_layout(exports_viz_component_viz_api_borrow_context_t ctx, exports_viz_component_viz_api_borrow_graph_t g);
bool exports_viz_component_viz_api_render(exports_viz_component_viz_api_borrow_context_t ctx, exports_viz_component_viz_api_borrow_graph_t g, viz_string_t *format, viz_string_t *ret, viz_string_t *err);

// Helper Functions

extern void exports_viz_component_viz_api_graph_drop_own(exports_viz_component_viz_api_own_graph_t handle);

extern exports_viz_component_viz_api_own_graph_t exports_viz_component_viz_api_graph_new(exports_viz_component_viz_api_graph_t *rep);
extern exports_viz_component_viz_api_graph_t* exports_viz_component_viz_api_graph_rep(exports_viz_component_viz_api_own_graph_t handle);
void exports_viz_component_viz_api_graph_destructor(exports_viz_component_viz_api_graph_t *rep);

extern void exports_viz_component_viz_api_node_drop_own(exports_viz_component_viz_api_own_node_t handle);

extern exports_viz_component_viz_api_own_node_t exports_viz_component_viz_api_node_new(exports_viz_component_viz_api_node_t *rep);
extern exports_viz_component_viz_api_node_t* exports_viz_component_viz_api_node_rep(exports_viz_component_viz_api_own_node_t handle);
void exports_viz_component_viz_api_node_destructor(exports_viz_component_viz_api_node_t *rep);

extern void exports_viz_component_viz_api_edge_drop_own(exports_viz_component_viz_api_own_edge_t handle);

extern exports_viz_component_viz_api_own_edge_t exports_viz_component_viz_api_edge_new(exports_viz_component_viz_api_edge_t *rep);
extern exports_viz_component_viz_api_edge_t* exports_viz_component_viz_api_edge_rep(exports_viz_component_viz_api_own_edge_t handle);
void exports_viz_component_viz_api_edge_destructor(exports_viz_component_viz_api_edge_t *rep);

extern void exports_viz_component_viz_api_context_drop_own(exports_viz_component_viz_api_own_context_t handle);

extern exports_viz_component_viz_api_own_context_t exports_viz_component_viz_api_context_new(exports_viz_component_viz_api_context_t *rep);
extern exports_viz_component_viz_api_context_t* exports_viz_component_viz_api_context_rep(exports_viz_component_viz_api_own_context_t handle);
void exports_viz_component_viz_api_context_destructor(exports_viz_component_viz_api_context_t *rep);

void exports_viz_component_viz_api_object_free(exports_viz_component_viz_api_object_t *ptr);

void viz_list_string_free(viz_list_string_t *ptr);

void exports_viz_component_viz_api_result_own_graph_string_free(exports_viz_component_viz_api_result_own_graph_string_t *ptr);

void exports_viz_component_viz_api_result_void_string_free(exports_viz_component_viz_api_result_void_string_t *ptr);

void exports_viz_component_viz_api_result_string_string_free(exports_viz_component_viz_api_result_string_string_t *ptr);

// Transfers ownership of `s` into the string `ret`
void viz_string_set(viz_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void viz_string_dup(viz_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void viz_string_free(viz_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
